#!/usr/bin/env bash
# RYSE — PreToolUse hook
# Bloque (exit 2) toute édition contenant des patterns interdits dans le code livrable.
# Lit le payload JSON de Claude Code sur stdin (tool_input.new_str / file_text / content).

set -euo pipefail

# Lire le JSON envoyé par Claude Code
payload=$(cat)

# Extraire le contenu qui va être écrit (selon le tool : Edit utilise new_str, Write utilise content)
content=$(echo "$payload" | jq -r '.tool_input.new_str // .tool_input.content // .tool_input.file_text // empty')

# Extraire le path pour ne checker que les fichiers projet pertinents
file_path=$(echo "$payload" | jq -r '.tool_input.file_path // empty')

# Skip les fichiers non-livrables (tasks/, lessons.md, scripts/, .claude/, README, docs)
case "$file_path" in
  */tasks/*|*/lessons.md|*/scripts/*|*/.claude/*|*/hooks/*|*/README*|*/docs/*|*/CLAUDE.md|*/CLIENT.md)
    exit 0
    ;;
esac

# Si pas de contenu à checker, on passe
if [ -z "$content" ]; then
  exit 0
fi

# Patterns interdits dans le code livrable
violations=()

# 1. Commentaires IA / origine (toutes syntaxes : //, /* */, <!-- -->, {% comment %})
if echo "$content" | grep -qiE 'generated by claude|generated by lovable|// claude|// AI[: ]|<!-- *(AI[: ]|lovable|claude)|/\* *(lovable|claude|ai[: ])|\{% comment %\} *(claude|lovable|TODO)|lovable:'; then
  violations+=("Commentaires IA/origine détectés (claude, lovable, /* Lovable: */, AI, TODO Claude…)")
fi

# 2. TODO / FIXME oubliés
if echo "$content" | grep -qE '(^|[^a-zA-Z])(TODO|FIXME|XXX|HACK)([^a-zA-Z]|$)'; then
  violations+=("TODO/FIXME/XXX/HACK détecté — résoudre ou supprimer avant commit")
fi

# 3. console.log / debugger / print de debug
if echo "$content" | grep -qE 'console\.(log|debug|warn)\(|debugger;|^\s*print\('; then
  violations+=("console.log/debugger/print de debug détecté")
fi

# 4. Noms de variables qui leakent l'origine
if echo "$content" | grep -qE 'aiGenerated|lovableTmp|claudeData|_v2_final|tmpClaude'; then
  violations+=("Variable avec nom qui leak l'origine IA (aiGenerated, lovableTmp, etc.)")
fi

# 5. Fichiers .liquid : default vide interdit sur text/richtext
if [[ "$file_path" == *.liquid ]] || [[ "$file_path" == *settings_schema.json ]] || [[ "$file_path" == */templates/*.json ]]; then
  if echo "$content" | grep -qE '"type":\s*"(text|textarea|richtext|inline_richtext)"[^}]*"default":\s*""'; then
    violations+=('"default": "" interdit sur text/textarea/richtext/inline_richtext — soit valeur réelle, soit retirer la clé')
  fi
fi

# Si violations : bloquer via JSON permissionDecision=deny.
# (exit 2 ne bloque PAS Edit/Write/MultiEdit dans Claude Code — cf issue #13744 ;
#  seul le JSON deny sur stdout est honoré, comme dans pre-edit-liquid-guard.sh.)
if [ ${#violations[@]} -gt 0 ]; then
  reason="❌ Édition bloquée — règles RYSE violées dans ${file_path} : "
  for v in "${violations[@]}"; do
    reason="${reason}• ${v} "
  done
  reason="${reason}— Corriger le contenu et réessayer. Si la règle est inadaptée à ce contexte, ajuster .claude/hooks/pre-edit-protect.sh"
  REASON="$reason" jq -nc '{
    "hookSpecificOutput": {
      "hookEventName": "PreToolUse",
      "permissionDecision": "deny",
      "permissionDecisionReason": env.REASON
    }
  }'
  exit 0
fi

# OK
exit 0
