name: Theme Check

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@58fd69afdfc30110f997ba9e212b302671e00d3b # v2.2.0
        with:
          token: ${{ github.token }}
          flags: "--fail-level error"
          theme_root: shopify-theme
          base: main
